// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrioritySetter.Data;

namespace PrioritySetter.Migrations
{
    [DbContext(typeof(PrioritySetterContext))]
    partial class PrioritySetterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PrioritySetter.Data.ErrorPriority", b =>
                {
                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriorityLevelId");

                    b.HasKey("Error");

                    b.HasIndex("PriorityLevel");

                    b.ToTable("ErrorPriorities");
                });

            modelBuilder.Entity("PrioritySetter.Data.Priority", b =>
                {
                    b.Property<int>("PriorityLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriorityLevelId");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PriorityLevel");

                    b.ToTable("DicPriorityLevels");

                    b.HasData(
                        new
                        {
                            PriorityLevel = 2,
                            Description = "Do it",
                            Name = "Normal"
                        },
                        new
                        {
                            PriorityLevel = 3,
                            Description = "Do it now!",
                            Name = "High"
                        },
                        new
                        {
                            PriorityLevel = 1,
                            Description = "Maybe later",
                            Name = "Low"
                        });
                });

            modelBuilder.Entity("PrioritySetter.Data.ErrorPriority", b =>
                {
                    b.HasOne("PrioritySetter.Data.Priority", "PriorityRelation")
                        .WithMany()
                        .HasForeignKey("PriorityLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriorityRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
